name: Build & Push to Github Packages
on:
  push:
    branches:
      - master
    paths:
      - "app/packages/web"
      - ".github/workflows/BuildAndPushWeb.yaml"
jobs:
  buildAndPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}

      - name: Build web Docker image
        run: |
          docker build --tag "docker.pkg.github.com/nikodem-wrona/mercury/mercury-web:dev" ./app/packages/web/
      - name: Push web Docker image
        run: |
          docker push "docker.pkg.github.com/nikodem-wrona/mercury/mercury-web:dev"
